"""Add delivery and seen status to messages

Revision ID: 380204557221
Revises: 3c8f097d3b81
Create Date: 2026-05-19 12:25:46.355698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '380204557221'
down_revision: Union[str, None] = '3c8f097d3b81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('is_delivered', sa.Boolean(), nullable=True))
    op.add_column('messages', sa.Column('is_seen', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'is_seen')
    op.drop_column('messages', 'is_delivered')
    # ### end Alembic commands ###
