"""Add delivery and seen status to messages

Revision ID: bd6ca7863cf4
Revises: 380204557221
Create Date: 2026-05-19 13:06:12.778702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd6ca7863cf4'
down_revision: Union[str, None] = '380204557221'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_sender_receiver', 'messages', ['sender_id', 'receiver_id'], unique=False)
    op.create_index('idx_timestamp', 'messages', ['timestamp'], unique=False)
    op.add_column('users', sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_seen')
    op.drop_index('idx_timestamp', table_name='messages')
    op.drop_index('idx_sender_receiver', table_name='messages')
    # ### end Alembic commands ###
